name: VoteSQL
main: me.javoris767.votesql.VoteSQL
version: 1.2
author: javoris767
authors: [javoris767, MCForger]
description: Votifier SQL/Listener/FlatFile Logger!
depends: [Votifier]
softdepend: [Vault]
commands:
    votesql:
        description: VoteSQL Command