# Thanks for choosing VoteSQL! Simply change the info below. The FlatFileListener on the first vote may not record it!
VoteSQL:
  onVote:
    Enabled: false
    # %P = Player Name %S = The Site they voted from!
    Message: '&2Thank you for voting %P from %S!'
  MySQL:
    Enabled: false
    Server: Server Address eg.Localhost
    Database: Place Database name here
    User: Place User of MySQL Database here
    Password: Place User password here
    Table_Prefix: votesql
  FlatFile:
    Enabled: false
  currency:
    Enabled: false
    Amount: 150
    # %P = Player Name %M = Money received.
    Message: '&2%P, You received %M dollars!'
  item:
    Enabled: false
    Message: '&2%P, You received items for voting!'
    # itemid:ammount
    items: 
    - 266:1
    - 1:5